#PE3

CREATE TABLE ADVENTURE_TRIP (
TRIP_ID DECIMAL,
TRIP_NAME VARCHAR(75),
START_LOCATION CHAR(50),
STATE CHAR(2),
DISTANCE NUMBER(10,2),
MAX_GRIP_SIZE NUMBER(10,2),
TYPE CHAR(20),
SEASON CHAR(20)
);

INSERT INTO ADVENTURE_TRIP(TRIP_ID,TRIP_NAME,START_LOCATION,STATE,DISTANCE,MAX_GRIP_SIZE,TYPE,SEASON) VALUES(45,'Jay Peak','Jay','VT',8,8,'Hiking and season','Summer') ;

DROP TABLE IF EXISTS ADVENTURE_TRIP;

CREATE TABLE TRIP (
TRIP_ID DECIMAL,
TRIP_NAME CHAR(75),
START_LOCATION CHAR(50),
STATE CHAR(2),
DISTANCE DECIMAL,
MAX_GRIP_SIZE DECIMAL,
TYPE CHAR(20),
SEASON CHAR(20)
);

CREATE TABLE GUIDE (
GUIDE_NUM CHAR(4),
LAST_NAME CHAR(15),
FIRST_NAME CHAR(15),
ADDRESS CHAR(25),
CITY CHAR(25),
STATE CHAR(2),
POSTAL_CODE CHAR(5),
PHONE_NUM CHAR(12),
HIRE_DATE DATE
);

CREATE TABLE RESERVATION (
RESERVATION_ID CHAR(7),
TRIP_ID DECIMAL,
TRIP_DATE DATE,
NUM_PERSONS DECIMAL,
TRIP_PRICE DECIMAL,
OTHER_FEES DECIMAL,
CUSTOMER_NUM CHAR(4)
);

CREATE TABLE TRIP_GUIDES (
TRIP_ID DECIMAL,
GUIDE_NUM CHAR(4)
);

DESCRIBE ADVENTURE_TRIP;
DESCRIBE TRIP;
DESCRIBE GUIDE;
DESCRIBE CUSTOMER;
DESCRIBE RESERVATION;
DESCRIBE TRIP_GUIDES;

SELECT * FROM ADVENTURE_TRIP;
SELECT * FROM TRIP;
SELECT * FROM GUIDE;
SELECT * FROM CUSTOMER;
SELECT * FROM RESERVATION;
SELECT * FROM TRIP_GUIDES;
